// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum SourcePlatform {
  tiktok,
  instagram,
  facebook,
  youtube,
  unknown,
}

/// Clasificacion tecnica del fallo (requerimiento seccion 8). El mensaje
/// exacto que ve el usuario vive en Dart (una tabla codigo -> texto en
/// espanol), no aqui: Kotlin solo diagnostica, no redacta copy de UI.
enum DownloadErrorCode {
  unsupportedLink,
  privateContent,
  contentRemoved,
  regionRestricted,
  fetchFailed,
  extractorOutdated,
  insufficientStorage,
  cancelled,
  networkLost,
  /// El ajuste "Solo con Wi-Fi" esta activo y no hay una red Wi-Fi disponible
  /// al momento de iniciar la descarga.
  wifiRequired,
  unknown,
}

class VideoFormatOption {
  VideoFormatOption({
    required this.formatId,
    required this.qualityLabel,
    required this.fileExtension,
    this.height,
    this.approxSizeBytes,
  });

  String formatId;

  /// Ya resuelto por Kotlin a partir de la altura/codec ("1080p", "720p").
  String qualityLabel;

  String fileExtension;

  int? height;

  int? approxSizeBytes;

  List<Object?> _toList() {
    return <Object?>[
      formatId,
      qualityLabel,
      fileExtension,
      height,
      approxSizeBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoFormatOption decode(Object result) {
    result as List<Object?>;
    return VideoFormatOption(
      formatId: result[0]! as String,
      qualityLabel: result[1]! as String,
      fileExtension: result[2]! as String,
      height: result[3] as int?,
      approxSizeBytes: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoFormatOption || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(formatId, other.formatId) && _deepEquals(qualityLabel, other.qualityLabel) && _deepEquals(fileExtension, other.fileExtension) && _deepEquals(height, other.height) && _deepEquals(approxSizeBytes, other.approxSizeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoFormatOption(formatId: $formatId, qualityLabel: $qualityLabel, fileExtension: $fileExtension, height: $height, approxSizeBytes: $approxSizeBytes)';
  }
}

class VideoAnalysis {
  VideoAnalysis({
    required this.sourceUrl,
    required this.platform,
    required this.title,
    this.author,
    this.thumbnailUrl,
    required this.durationSeconds,
    required this.formats,
    required this.audioFormats,
  });

  String sourceUrl;

  SourcePlatform platform;

  String title;

  String? author;

  String? thumbnailUrl;

  int durationSeconds;

  List<VideoFormatOption> formats;

  /// Calidades de solo-audio (extraccion con ffmpeg), separadas de [formats]
  /// porque no tienen altura y se seleccionan desde un modo aparte en la UI
  /// ("Video" / "Solo audio").
  List<VideoFormatOption> audioFormats;

  List<Object?> _toList() {
    return <Object?>[
      sourceUrl,
      platform,
      title,
      author,
      thumbnailUrl,
      durationSeconds,
      formats,
      audioFormats,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoAnalysis decode(Object result) {
    result as List<Object?>;
    return VideoAnalysis(
      sourceUrl: result[0]! as String,
      platform: result[1]! as SourcePlatform,
      title: result[2]! as String,
      author: result[3] as String?,
      thumbnailUrl: result[4] as String?,
      durationSeconds: result[5]! as int,
      formats: (result[6]! as List<Object?>).cast<VideoFormatOption>(),
      audioFormats: (result[7]! as List<Object?>).cast<VideoFormatOption>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoAnalysis || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourceUrl, other.sourceUrl) && _deepEquals(platform, other.platform) && _deepEquals(title, other.title) && _deepEquals(author, other.author) && _deepEquals(thumbnailUrl, other.thumbnailUrl) && _deepEquals(durationSeconds, other.durationSeconds) && _deepEquals(formats, other.formats) && _deepEquals(audioFormats, other.audioFormats);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoAnalysis(sourceUrl: $sourceUrl, platform: $platform, title: $title, author: $author, thumbnailUrl: $thumbnailUrl, durationSeconds: $durationSeconds, formats: $formats, audioFormats: $audioFormats)';
  }
}

/// Union por nulabilidad: si [errorCode] es nulo, [video] esta presente y la
/// operacion tuvo exito; si no, [video] es nulo. Evita modelar una clase
/// sellada que Pigeon no puede expresar de forma nativa.
class AnalysisResult {
  AnalysisResult({
    this.video,
    this.errorCode,
    this.errorDetail,
  });

  VideoAnalysis? video;

  DownloadErrorCode? errorCode;

  /// Texto tecnico crudo (stderr de yt-dlp) solo para el registro local de
  /// diagnostico; nunca se muestra al usuario tal cual.
  String? errorDetail;

  List<Object?> _toList() {
    return <Object?>[
      video,
      errorCode,
      errorDetail,
    ];
  }

  Object encode() {
    return _toList();  }

  static AnalysisResult decode(Object result) {
    result as List<Object?>;
    return AnalysisResult(
      video: result[0] as VideoAnalysis?,
      errorCode: result[1] as DownloadErrorCode?,
      errorDetail: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AnalysisResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(video, other.video) && _deepEquals(errorCode, other.errorCode) && _deepEquals(errorDetail, other.errorDetail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AnalysisResult(video: $video, errorCode: $errorCode, errorDetail: $errorDetail)';
  }
}

class DownloadRequest {
  DownloadRequest({
    required this.downloadId,
    required this.sourceUrl,
    required this.platform,
    required this.formatId,
    required this.suggestedFileName,
    required this.wifiOnly,
    required this.audioOnly,
    this.approxTotalBytes,
  });

  /// Generado en Dart antes de llamar a `startDownload`, no por Kotlin: la
  /// fila de historial y la notificacion en primer plano necesitan un id
  /// estable desde antes de que exista ninguna respuesta nativa, para que no
  /// haya una ventana donde un evento de progreso llegue sin id que lo
  /// reciba.
  String downloadId;

  String sourceUrl;

  SourcePlatform platform;

  String formatId;

  String suggestedFileName;

  bool wifiOnly;

  /// true = extraer solo el audio (yt-dlp -x + ffmpeg) en vez del video
  /// completo; [formatId] en ese caso es uno de los ids sinteticos de
  /// [VideoAnalysis.audioFormats] ("audio-192", etc.), no un formato real de
  /// yt-dlp.
  bool audioOnly;

  /// Tamaño aproximado que ya se conocia desde el analisis (seccion 4, Vista
  /// previa). Se reenvia para que el progreso pueda mostrar MB descargados
  /// sin que Kotlin tenga que volver a inferirlo.
  int? approxTotalBytes;

  List<Object?> _toList() {
    return <Object?>[
      downloadId,
      sourceUrl,
      platform,
      formatId,
      suggestedFileName,
      wifiOnly,
      audioOnly,
      approxTotalBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static DownloadRequest decode(Object result) {
    result as List<Object?>;
    return DownloadRequest(
      downloadId: result[0]! as String,
      sourceUrl: result[1]! as String,
      platform: result[2]! as SourcePlatform,
      formatId: result[3]! as String,
      suggestedFileName: result[4]! as String,
      wifiOnly: result[5]! as bool,
      audioOnly: result[6]! as bool,
      approxTotalBytes: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(downloadId, other.downloadId) && _deepEquals(sourceUrl, other.sourceUrl) && _deepEquals(platform, other.platform) && _deepEquals(formatId, other.formatId) && _deepEquals(suggestedFileName, other.suggestedFileName) && _deepEquals(wifiOnly, other.wifiOnly) && _deepEquals(audioOnly, other.audioOnly) && _deepEquals(approxTotalBytes, other.approxTotalBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DownloadRequest(downloadId: $downloadId, sourceUrl: $sourceUrl, platform: $platform, formatId: $formatId, suggestedFileName: $suggestedFileName, wifiOnly: $wifiOnly, audioOnly: $audioOnly, approxTotalBytes: $approxTotalBytes)';
  }
}

class ExtractorUpdateResult {
  ExtractorUpdateResult({
    required this.updated,
    this.versionName,
  });

  /// true = se actualizo a una version nueva; false = ya estaba al dia.
  bool updated;

  String? versionName;

  List<Object?> _toList() {
    return <Object?>[
      updated,
      versionName,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExtractorUpdateResult decode(Object result) {
    result as List<Object?>;
    return ExtractorUpdateResult(
      updated: result[0]! as bool,
      versionName: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExtractorUpdateResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(updated, other.updated) && _deepEquals(versionName, other.versionName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExtractorUpdateResult(updated: $updated, versionName: $versionName)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SourcePlatform) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is DownloadErrorCode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is VideoFormatOption) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is VideoAnalysis) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AnalysisResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ExtractorUpdateResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SourcePlatform.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : DownloadErrorCode.values[value];
      case 131:
        return VideoFormatOption.decode(readValue(buffer)!);
      case 132:
        return VideoAnalysis.decode(readValue(buffer)!);
      case 133:
        return AnalysisResult.decode(readValue(buffer)!);
      case 134:
        return DownloadRequest.decode(readValue(buffer)!);
      case 135:
        return ExtractorUpdateResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DownloadEngineHostApi {
  /// Constructor for [DownloadEngineHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DownloadEngineHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Inicializa yt-dlp y ffmpeg. Debe llamarse una sola vez por proceso,
  /// antes de cualquier otro metodo; es costosa (extrae binarios la primera
  /// vez) por lo que se ejecuta en el arranque de la app, no por cada enlace.
  Future<void> initialize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<AnalysisResult> analyzeUrl(String url) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.analyzeUrl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[url]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AnalysisResult;
  }

  /// No bloquea: encola la descarga en el servicio en primer plano y
  /// retorna. El resultado llega despues por
  /// onDownloadCompleted/onDownloadFailed.
  Future<void> startDownload(DownloadRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.startDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelDownload(String downloadId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.cancelDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[downloadId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<ExtractorUpdateResult> updateExtractor() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.updateExtractor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ExtractorUpdateResult;
  }

  Future<String?> currentExtractorVersion() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.currentExtractorVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }
}

abstract class DownloadEngineFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onDownloadProgress(String downloadId, double percent, int? etaSeconds, int downloadedBytes, int? totalBytes);

  void onDownloadCompleted(String downloadId, String savedUri, String fileName, int sizeBytes);

  void onDownloadFailed(String downloadId, DownloadErrorCode errorCode, String? errorDetail);

  static void setUp(DownloadEngineFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nuvclip.DownloadEngineFlutterApi.onDownloadProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_downloadId = args[0]! as String;
          final double arg_percent = args[1]! as double;
          final int? arg_etaSeconds = args[2] as int?;
          final int arg_downloadedBytes = args[3]! as int;
          final int? arg_totalBytes = args[4] as int?;
          try {
            api.onDownloadProgress(arg_downloadId, arg_percent, arg_etaSeconds, arg_downloadedBytes, arg_totalBytes);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nuvclip.DownloadEngineFlutterApi.onDownloadCompleted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_downloadId = args[0]! as String;
          final String arg_savedUri = args[1]! as String;
          final String arg_fileName = args[2]! as String;
          final int arg_sizeBytes = args[3]! as int;
          try {
            api.onDownloadCompleted(arg_downloadId, arg_savedUri, arg_fileName, arg_sizeBytes);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nuvclip.DownloadEngineFlutterApi.onDownloadFailed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_downloadId = args[0]! as String;
          final DownloadErrorCode arg_errorCode = args[1]! as DownloadErrorCode;
          final String? arg_errorDetail = args[2] as String?;
          try {
            api.onDownloadFailed(arg_downloadId, arg_errorCode, arg_errorDetail);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
