// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nuvclip.app.downloader

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DownloadEngineApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class SourcePlatform(val raw: Int) {
  TIKTOK(0),
  INSTAGRAM(1),
  FACEBOOK(2),
  YOUTUBE(3),
  UNKNOWN(4);

  companion object {
    fun ofRaw(raw: Int): SourcePlatform? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Clasificacion tecnica del fallo (requerimiento seccion 8). El mensaje
 * exacto que ve el usuario vive en Dart (una tabla codigo -> texto en
 * espanol), no aqui: Kotlin solo diagnostica, no redacta copy de UI.
 */
enum class DownloadErrorCode(val raw: Int) {
  UNSUPPORTED_LINK(0),
  PRIVATE_CONTENT(1),
  CONTENT_REMOVED(2),
  REGION_RESTRICTED(3),
  FETCH_FAILED(4),
  EXTRACTOR_OUTDATED(5),
  INSUFFICIENT_STORAGE(6),
  CANCELLED(7),
  NETWORK_LOST(8),
  /**
   * El ajuste "Solo con Wi-Fi" esta activo y no hay una red Wi-Fi disponible
   * al momento de iniciar la descarga.
   */
  WIFI_REQUIRED(9),
  UNKNOWN(10);

  companion object {
    fun ofRaw(raw: Int): DownloadErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoFormatOption (
  val formatId: String,
  /** Ya resuelto por Kotlin a partir de la altura/codec ("1080p", "720p"). */
  val qualityLabel: String,
  val fileExtension: String,
  val height: Long? = null,
  val approxSizeBytes: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoFormatOption {
      val formatId = pigeonVar_list[0] as String
      val qualityLabel = pigeonVar_list[1] as String
      val fileExtension = pigeonVar_list[2] as String
      val height = pigeonVar_list[3] as Long?
      val approxSizeBytes = pigeonVar_list[4] as Long?
      return VideoFormatOption(formatId, qualityLabel, fileExtension, height, approxSizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      formatId,
      qualityLabel,
      fileExtension,
      height,
      approxSizeBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoFormatOption
    return DownloadEngineApiPigeonUtils.deepEquals(this.formatId, other.formatId) && DownloadEngineApiPigeonUtils.deepEquals(this.qualityLabel, other.qualityLabel) && DownloadEngineApiPigeonUtils.deepEquals(this.fileExtension, other.fileExtension) && DownloadEngineApiPigeonUtils.deepEquals(this.height, other.height) && DownloadEngineApiPigeonUtils.deepEquals(this.approxSizeBytes, other.approxSizeBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.formatId)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.qualityLabel)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.fileExtension)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.height)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.approxSizeBytes)
    return result
  }
  override fun toString(): String {
    return "VideoFormatOption(formatId=$formatId, qualityLabel=$qualityLabel, fileExtension=$fileExtension, height=$height, approxSizeBytes=$approxSizeBytes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoAnalysis (
  val sourceUrl: String,
  val platform: SourcePlatform,
  val title: String,
  val author: String? = null,
  val thumbnailUrl: String? = null,
  val durationSeconds: Long,
  val formats: List<VideoFormatOption>,
  /**
   * Calidades de solo-audio (extraccion con ffmpeg), separadas de [formats]
   * porque no tienen altura y se seleccionan desde un modo aparte en la UI
   * ("Video" / "Solo audio").
   */
  val audioFormats: List<VideoFormatOption>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoAnalysis {
      val sourceUrl = pigeonVar_list[0] as String
      val platform = pigeonVar_list[1] as SourcePlatform
      val title = pigeonVar_list[2] as String
      val author = pigeonVar_list[3] as String?
      val thumbnailUrl = pigeonVar_list[4] as String?
      val durationSeconds = pigeonVar_list[5] as Long
      val formats = pigeonVar_list[6] as List<VideoFormatOption>
      val audioFormats = pigeonVar_list[7] as List<VideoFormatOption>
      return VideoAnalysis(sourceUrl, platform, title, author, thumbnailUrl, durationSeconds, formats, audioFormats)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceUrl,
      platform,
      title,
      author,
      thumbnailUrl,
      durationSeconds,
      formats,
      audioFormats,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoAnalysis
    return DownloadEngineApiPigeonUtils.deepEquals(this.sourceUrl, other.sourceUrl) && DownloadEngineApiPigeonUtils.deepEquals(this.platform, other.platform) && DownloadEngineApiPigeonUtils.deepEquals(this.title, other.title) && DownloadEngineApiPigeonUtils.deepEquals(this.author, other.author) && DownloadEngineApiPigeonUtils.deepEquals(this.thumbnailUrl, other.thumbnailUrl) && DownloadEngineApiPigeonUtils.deepEquals(this.durationSeconds, other.durationSeconds) && DownloadEngineApiPigeonUtils.deepEquals(this.formats, other.formats) && DownloadEngineApiPigeonUtils.deepEquals(this.audioFormats, other.audioFormats)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.sourceUrl)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.platform)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.title)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.author)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.thumbnailUrl)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.durationSeconds)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.formats)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.audioFormats)
    return result
  }
  override fun toString(): String {
    return "VideoAnalysis(sourceUrl=$sourceUrl, platform=$platform, title=$title, author=$author, thumbnailUrl=$thumbnailUrl, durationSeconds=$durationSeconds, formats=$formats, audioFormats=$audioFormats)"
  }
}

/**
 * Union por nulabilidad: si [errorCode] es nulo, [video] esta presente y la
 * operacion tuvo exito; si no, [video] es nulo. Evita modelar una clase
 * sellada que Pigeon no puede expresar de forma nativa.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AnalysisResult (
  val video: VideoAnalysis? = null,
  val errorCode: DownloadErrorCode? = null,
  /**
   * Texto tecnico crudo (stderr de yt-dlp) solo para el registro local de
   * diagnostico; nunca se muestra al usuario tal cual.
   */
  val errorDetail: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnalysisResult {
      val video = pigeonVar_list[0] as VideoAnalysis?
      val errorCode = pigeonVar_list[1] as DownloadErrorCode?
      val errorDetail = pigeonVar_list[2] as String?
      return AnalysisResult(video, errorCode, errorDetail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      video,
      errorCode,
      errorDetail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AnalysisResult
    return DownloadEngineApiPigeonUtils.deepEquals(this.video, other.video) && DownloadEngineApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && DownloadEngineApiPigeonUtils.deepEquals(this.errorDetail, other.errorDetail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.video)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.errorDetail)
    return result
  }
  override fun toString(): String {
    return "AnalysisResult(video=$video, errorCode=$errorCode, errorDetail=$errorDetail)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadRequest (
  /**
   * Generado en Dart antes de llamar a `startDownload`, no por Kotlin: la
   * fila de historial y la notificacion en primer plano necesitan un id
   * estable desde antes de que exista ninguna respuesta nativa, para que no
   * haya una ventana donde un evento de progreso llegue sin id que lo
   * reciba.
   */
  val downloadId: String,
  val sourceUrl: String,
  val platform: SourcePlatform,
  val formatId: String,
  val suggestedFileName: String,
  val wifiOnly: Boolean,
  /**
   * true = extraer solo el audio (yt-dlp -x + ffmpeg) en vez del video
   * completo; [formatId] en ese caso es uno de los ids sinteticos de
   * [VideoAnalysis.audioFormats] ("audio-192", etc.), no un formato real de
   * yt-dlp.
   */
  val audioOnly: Boolean,
  /**
   * Altura elegida en video. Permite volver a analizar y escoger el formato
   * equivalente si una actualización de yt-dlp cambia sus ids internos.
   * Es nula en modo audio.
   */
  val requestedHeight: Long? = null,
  /**
   * Tamaño aproximado que ya se conocia desde el analisis (seccion 4, Vista
   * previa). Se reenvia para que el progreso pueda mostrar MB descargados
   * sin que Kotlin tenga que volver a inferirlo.
   */
  val approxTotalBytes: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadRequest {
      val downloadId = pigeonVar_list[0] as String
      val sourceUrl = pigeonVar_list[1] as String
      val platform = pigeonVar_list[2] as SourcePlatform
      val formatId = pigeonVar_list[3] as String
      val suggestedFileName = pigeonVar_list[4] as String
      val wifiOnly = pigeonVar_list[5] as Boolean
      val audioOnly = pigeonVar_list[6] as Boolean
      val requestedHeight = pigeonVar_list[7] as Long?
      val approxTotalBytes = pigeonVar_list[8] as Long?
      return DownloadRequest(downloadId, sourceUrl, platform, formatId, suggestedFileName, wifiOnly, audioOnly, requestedHeight, approxTotalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      downloadId,
      sourceUrl,
      platform,
      formatId,
      suggestedFileName,
      wifiOnly,
      audioOnly,
      requestedHeight,
      approxTotalBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DownloadRequest
    return DownloadEngineApiPigeonUtils.deepEquals(this.downloadId, other.downloadId) && DownloadEngineApiPigeonUtils.deepEquals(this.sourceUrl, other.sourceUrl) && DownloadEngineApiPigeonUtils.deepEquals(this.platform, other.platform) && DownloadEngineApiPigeonUtils.deepEquals(this.formatId, other.formatId) && DownloadEngineApiPigeonUtils.deepEquals(this.suggestedFileName, other.suggestedFileName) && DownloadEngineApiPigeonUtils.deepEquals(this.wifiOnly, other.wifiOnly) && DownloadEngineApiPigeonUtils.deepEquals(this.audioOnly, other.audioOnly) && DownloadEngineApiPigeonUtils.deepEquals(this.requestedHeight, other.requestedHeight) && DownloadEngineApiPigeonUtils.deepEquals(this.approxTotalBytes, other.approxTotalBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.downloadId)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.sourceUrl)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.platform)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.formatId)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.suggestedFileName)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.wifiOnly)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.audioOnly)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.requestedHeight)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.approxTotalBytes)
    return result
  }
  override fun toString(): String {
    return "DownloadRequest(downloadId=$downloadId, sourceUrl=$sourceUrl, platform=$platform, formatId=$formatId, suggestedFileName=$suggestedFileName, wifiOnly=$wifiOnly, audioOnly=$audioOnly, requestedHeight=$requestedHeight, approxTotalBytes=$approxTotalBytes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExtractorUpdateResult (
  /** true = se actualizo a una version nueva; false = ya estaba al dia. */
  val updated: Boolean,
  val versionName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExtractorUpdateResult {
      val updated = pigeonVar_list[0] as Boolean
      val versionName = pigeonVar_list[1] as String?
      return ExtractorUpdateResult(updated, versionName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      updated,
      versionName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExtractorUpdateResult
    return DownloadEngineApiPigeonUtils.deepEquals(this.updated, other.updated) && DownloadEngineApiPigeonUtils.deepEquals(this.versionName, other.versionName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.updated)
    result = 31 * result + DownloadEngineApiPigeonUtils.deepHash(this.versionName)
    return result
  }
  override fun toString(): String {
    return "ExtractorUpdateResult(updated=$updated, versionName=$versionName)"
  }
}
private open class DownloadEngineApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SourcePlatform.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DownloadErrorCode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoFormatOption.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoAnalysis.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalysisResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExtractorUpdateResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SourcePlatform -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is DownloadErrorCode -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is VideoFormatOption -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VideoAnalysis -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AnalysisResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is DownloadRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ExtractorUpdateResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DownloadEngineHostApi {
  /**
   * Inicializa yt-dlp y ffmpeg. Debe llamarse una sola vez por proceso,
   * antes de cualquier otro metodo; es costosa (extrae binarios la primera
   * vez) por lo que se ejecuta en el arranque de la app, no por cada enlace.
   */
  fun initialize(callback: (Result<Unit>) -> Unit)
  fun analyzeUrl(url: String, callback: (Result<AnalysisResult>) -> Unit)
  /**
   * No bloquea: encola la descarga en el servicio en primer plano y
   * retorna. El resultado llega despues por
   * onDownloadCompleted/onDownloadFailed.
   */
  fun startDownload(request: DownloadRequest)
  fun cancelDownload(downloadId: String)
  fun updateExtractor(callback: (Result<ExtractorUpdateResult>) -> Unit)
  fun currentExtractorVersion(): String?

  companion object {
    /** The codec used by DownloadEngineHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DownloadEngineApiPigeonCodec()
    }
    /** Sets up an instance of `DownloadEngineHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DownloadEngineHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initialize{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DownloadEngineApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(DownloadEngineApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.analyzeUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.analyzeUrl(urlArg) { result: Result<AnalysisResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DownloadEngineApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(DownloadEngineApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.startDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DownloadRequest
            val wrapped: List<Any?> = try {
              api.startDownload(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              DownloadEngineApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.cancelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val downloadIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelDownload(downloadIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              DownloadEngineApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.updateExtractor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.updateExtractor{ result: Result<ExtractorUpdateResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DownloadEngineApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(DownloadEngineApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuvclip.DownloadEngineHostApi.currentExtractorVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.currentExtractorVersion())
            } catch (exception: Throwable) {
              DownloadEngineApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DownloadEngineFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DownloadEngineFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      DownloadEngineApiPigeonCodec()
    }
  }
  /**
   * Push transitorio: `analyzeUrl` detecto EXTRACTOR_OUTDATED, esta
   * descargando un yt-dlp nuevo y va a reintentar el analisis original
   * automaticamente. Sin esto la UI no tiene forma de distinguir esta
   * espera extra de un analisis normal.
   */
  fun onExtractorAutoUpdating(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuvclip.DownloadEngineFlutterApi.onExtractorAutoUpdating$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DownloadEngineApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDownloadProgress(downloadIdArg: String, percentArg: Double, etaSecondsArg: Long?, downloadedBytesArg: Long, totalBytesArg: Long?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuvclip.DownloadEngineFlutterApi.onDownloadProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(downloadIdArg, percentArg, etaSecondsArg, downloadedBytesArg, totalBytesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DownloadEngineApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDownloadCompleted(downloadIdArg: String, savedUriArg: String, fileNameArg: String, sizeBytesArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuvclip.DownloadEngineFlutterApi.onDownloadCompleted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(downloadIdArg, savedUriArg, fileNameArg, sizeBytesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DownloadEngineApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDownloadFailed(downloadIdArg: String, errorCodeArg: DownloadErrorCode, errorDetailArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuvclip.DownloadEngineFlutterApi.onDownloadFailed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(downloadIdArg, errorCodeArg, errorDetailArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DownloadEngineApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
